const Drivers = [

    {
      id: "CP-BK 436",
      name: "Ali Ahmed",
      phone: "+92 318 028882",
      car: "Alto MINI-BPW-124",
      passenger: "3-Passenger",
      zone: "Gulistan e Johar",
      startLocation: "Kamran Chowrangi",
      endLocation: "Nazimabad 7 Number Bus Stop",
      image: "/assets/imgs/image.png", 

    },
    {
      id: "CP-BK 501",
      name: "Raza Shafiq",
      phone: "+92 318 028882",
      car: "Alto MINI-BPW-124",
      passenger: "3-Passenger",
      zone: "Gulistan e Johar",
      startLocation: "Kamran Chowrangi",
      endLocation: "Nazimabad 7 Number Bus Stop",
    },
    {
      id: "CP-BK 325",
      name: "Ali Ahmed",
      phone: "+92 318 028882",
      car: "Alto MINI-BPW-124",
      passenger: "3-Passenger",
      zone: "Gulistan e Johar",
      startLocation: "Kamran Chowrangi",
      endLocation: "Nazimabad 7 Number Bus Stop",
    },
    {
      id: "CP-BK 712",
      name: "Ali Ahmed",
      phone: "+92 318 028882",
      car: "Alto MINI-BPW-124",
      passenger: "3-Passenger",
      zone: "Gulistan e Johar",
      startLocation: "Kamran Chowrangi",
      endLocation: "Nazimabad 7 Number Bus Stop",
    },
    {
      id: "CP-BK 876",
      name: "Ali Ahmed",
      phone: "+92 318 028882",
      car: "Alto MINI-BPW-124",
      passenger: "3-Passenger",
      zone: "Gulistan e Johar",
      startLocation: "Kamran Chowrangi",
      endLocation: "Nazimabad 7 Number Bus Stop",
    },
    {
      id: "CP-BK 440",
      name: "Ali Ahmed",
      phone: "+92 318 028882",
      car: "Alto MINI-BPW-124",
      passenger: "3-Passenger",
      zone: "Gulistan e Johar",
      startLocation: "Kamran Chowrangi",
      endLocation: "Nazimabad 7 Number Bus Stop",
    },
    {
      id: "CP-BK 618",
      name: "Ali Ahmed",
      phone: "+92 318 028882",
      car: "Alto MINI-BPW-124",
      passenger: "3-Passenger",
      zone: "Gulistan e Johar",
      startLocation: "Kamran Chowrangi",
      endLocation: "Nazimabad 7 Number Bus Stop",
    },
    {
      id: "CP-BK 203",
      name: "Ahmed khan",
      phone: "+92 318 028882",
      car: "Alto MINI-BPW-124",
      passenger: "3-Passenger",
      zone: "Gulistan e Johar",
      startLocation: "Kamran Chowrangi",
      endLocation: "Nazimabad 7 Number Bus Stop",
    },
  ];
  export default Drivers